### ISSUE TITLE
Scripts for qiime analyses for alpha rarefaction

### ISSUE THREAD

**Issue by EugeneMwanza** [nickallsing/TJ_River_Project#2]
Hi @nickallsing @nallsing-salk 
Very interesting research you guys did. I was trying to replicate your methodology but then I figured there were no qiime analysis scripts. I managed to import the modified OTU table to qiime but I have trouble running the alpha rarefaction part as it requires a phylogenetic tree and I was wondering how you guys did it. Did you have a phylogenetic tree? Because Kaiju doesn't provide one. Please advise on what to do and help with the qiime scripts a swell.

**Comment by nallsing-salk** [comment]
Hello and thank you for checking out these scripts! I believe that for the core alpha diversity metrics a phylogenetic tree is not required. I would suggest checking out the [Qiime2 Moving Pictures Tutorial](https://docs.qiime2.org/2024.5/tutorials/moving-pictures/). It has examples of analyzing alpha and beta diversity.
